# Generated by Django 2.2.1 on 2019-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_passwordresetcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcodes',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
