# Generated by Django 2.2.1 on 2019-05-26 12:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_accountsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsetting',
            name='tag',
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='comment',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[], size=100),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='comment_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='comments_per_day',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='follow_per_day',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='follow_time',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='like_per_day',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='max_like_for_one_tag',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='tag_blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='tag_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='unfollow_per_day',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='unfollow_whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='unwanted_username_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='user_blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
