# Generated by Django 2.2.1 on 2019-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_accountsetting_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
