# Generated by Django 2.2.1 on 2019-05-26 12:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_accountsetting_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='unfollow_whitelist',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default=[], size=20),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='unwanted_username_list',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default=[], size=20),
        ),
    ]
