# Generated by Django 2.2.1 on 2019-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_accountreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='follow_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountreport',
            name='unfollow_number',
            field=models.IntegerField(default=0),
        ),
    ]
